spring:
  application:
    name: franchise-api
  r2dbc:
    url: r2dbc:mysql://${RDS_HOSTNAME:127.0.0.1}:${RDS_PORT:3307}/${RDS_DB_NAME:franchise}?sslMode=disabled
    username: ${RDS_DB_USERNAME:root}
    password: ${RDS_DB_PASSWORD:t5xsm+kt8A}
  jackson:
    property-naming-strategy: SNAKE_CASE
 
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.accenture: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
